<?php

/**
 * @file
 * Enhances file adminstration by adding published, promote, and sticky fields.
 */

/**
 * File is not published.
 */
define('FILE_NOT_PUBLISHED', 0);

/**
 * File is published.
 */
define('FILE_PUBLISHED', 1);

/**
 * File is not promoted.
 */
define('FILE_NOT_PROMOTED', 0);

/**
 * File is promoted.
 */
define('FILE_PROMOTED', 1);

/**
 * File is not sticky at top of a list.
 */
define('FILE_NOT_STICKY', 0);

/**
 * File is sticky at top of a list.
 */
define('FILE_STICKY', 1);

/**
 * Implements hook_permission().
 */
function file_admin_permission() {
  $perms = array(
    'view own unpublished media' => array(
      'title' => t('View own unpublished media'),
    ),
  );

  return $perms;
}

/**
 * Implements hook_entity_insert().
 *
 * Set created timestamp when entity is created.
 */
function file_admin_entity_presave($entity, $type) {
  if ($type == 'file' && !isset($entity->fid)) {
    $entity->created = REQUEST_TIME;
    $file_options = variable_get('file_admin_file_options_' . $entity->type, array('published'));
    foreach ($file_options as $setting) {
      $entity->$setting = 1;
    }
  }
}

/**
 * Implements hook_menu().
 *
 * @see file_entity_menu().
 */
function file_admin_menu() {
  $items = array();

  // Attach a "Settings" tab to each file type in the same way that
  // Field UI attaches "Manage fields" and "Manage display" tabs. Note that
  // Field UI does not have to be enabled; we're just using the same IA pattern
  // here for attaching the "Settings" page.
  $entity_info = entity_get_info('file');
  foreach ($entity_info['bundles'] as $file_type => $bundle_info) {
    if (isset($bundle_info['admin'])) {
      // Get the base path and access.
      $path = $bundle_info['admin']['path'];
      $access = array_intersect_key($bundle_info['admin'], drupal_map_assoc(array('access callback', 'access arguments')));
      $access += array(
        'access callback' => 'user_access',
        'access arguments' => array('administer file types'),
      );

      // The file type must be passed to the page callbacks. It might be
      // configured as a wildcard (multiple file types sharing the same menu
      // router path).
      $file_type_argument = isset($bundle_info['admin']['bundle argument']) ? $bundle_info['admin']['bundle argument'] : $file_type;

      // Add the 'settings' tab.
      $items["$path/settings"] = array(
        'title' => 'Settings',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('file_admin_file_type_settings_form', $file_type_argument),
        'type' => MENU_LOCAL_TASK,
        'weight' => -1,
        'file' => 'file_admin.admin.inc',
      ) + $access;
    }
  }

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter() for file_entity_admin.
 *
 * Add a published field to the file adminstration form.
 */
function file_admin_form_file_entity_admin_files_alter(&$form, &$form_state) {
  // Only act if we're in a list display mode.
  // TODO: find a less awkward way to determine the mode.
  if (is_null(arg(3))) {
    $limit = variable_get('file_entity_admin_files_limit', 50);

    $operations_header = array_pop($form['files']['#header']);
    $form['files']['#header']['published'] = array('data' => t('Published'), 'field' => 'f.published');
    $form['files']['#header']['operations'] = $operations_header;
    $files = $form['files']['#options'];

    $query = db_select('file_managed', 'f')->extend('PagerDefault')->extend('TableSort');

    $result = $query
      ->fields('f', array('fid', 'published'))
      ->condition('f.status', FILE_STATUS_PERMANENT)
      ->limit($limit)
      ->orderByHeader($form['files']['#header'])
      ->execute();

    foreach ($result as $file) {
      $operations_row = array_pop($form['files']['#options'][$file->fid]);
      $form['files']['#options'][$file->fid]['published'] = $file->published ? t('published') : t('not published');
      $form['files']['#options'][$file->fid]['operations'] = $operations_row;
    }
  }
}

/**
 * Implements hook_views_api().
 */
function file_admin_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'file_admin') . '/includes',
  );
}

/**
 * Implements hook_page_alter().
 *
 * Add settings links to the file type overview page.
 */
function file_admin_page_alter(&$page) {
  if (isset($page['content']['system_main']['file_type_table'])) {
    $types = file_info_file_types();
    $entity_info = entity_get_info('file');
    $i = 0;
    // We're adding a column.
    $page['content']['system_main']['file_type_table']['#header'][1]['colspan']++;
    foreach ($types as $type => $info) {
      $path = isset($entity_info['bundles'][$type]['admin']['real path']) ? $entity_info['bundles'][$type]['admin']['real path'] : NULL;
      // Insert the new column after the existing file type label row.
      array_splice($page['content']['system_main']['file_type_table']['#rows'][$i], 1, 0, array('data' => isset($path) ? l(t('settings'), $path . '/settings') : ''));
      $i++;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for form_file_entity_edit.
 */
function file_admin_form_file_entity_edit_alter(&$form, &$form_state) {
  $file = file_load($form['fid']['#value']);
  $user = user_load($file->uid);
  $file->name = $user->name;
  $file->date = format_date($file->created, 'custom', 'Y-m-d H:i:s O');
  if ($help = variable_get('file_admin_help_' . $form['#bundle'], '')) {
    $form['#prefix'] = (isset($form['#prefix']) ? $form['#prefix'] : '') . '<p>' . filter_xss_admin($help) . '</p>';
  }

  // Basic file information.
  // These elements are just values so they are not even sent to the client.
  foreach (array('created', 'uid') as $key) {
    $form[$key] = array(
      '#type' => 'value',
      '#value' => isset($file->$key) ? $file->$key : NULL,
    );
  }

  $form['additional_settings'] = array(
    '#type' => 'vertical_tabs',
    '#weight' => 99,
  );
  // File author information for administrators
  $form['author'] = array(
    '#type' => 'fieldset',
    '#access' => user_access('administer files'),
    '#title' => t('Authoring information'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'additional_settings',
    '#attributes' => array(
      'class' => array('file-entity-form-author'),
    ),
    '#attached' => array(
      'js' => array(
        drupal_get_path('module', 'file_admin') . '/file_admin.js',
        array(
          'type' => 'setting',
          'data' => array('anonymous' => variable_get('anonymous', t('Anonymous'))),
        ),
      ),
    ),
    '#weight' => 90,
  );
  $form['author']['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Authored by'),
    '#maxlength' => 60,
    '#autocomplete_path' => 'user/autocomplete',
    '#default_value' => !empty($file->name) ? $file->name : '',
    '#weight' => -1,
    '#description' => t('Leave blank for %anonymous.', array('%anonymous' => variable_get('anonymous', t('Anonymous')))),
  );
  $form['author']['date'] = array(
    '#type' => 'textfield',
    '#title' => t('Posted on'),
    '#maxlength' => 25,
    '#description' => t('Format: %time. The date format is YYYY-MM-DD and %timezone is the time zone offset from UTC. Leave blank to use the time of form submission.', array('%time' => !empty($file->date) ? date_format(date_create($file->date), 'Y-m-d H:i:s O') : format_date($file->created, 'custom', 'Y-m-d H:i:s O'), '%timezone' => !empty($file->date) ? date_format(date_create($file->date), 'O') : format_date($file->created, 'custom', 'O'))),
    '#default_value' => !empty($file->date) ? $file->date : '',
  );
  $form['author']['date'] = array(
    '#type' => 'textfield',
    '#title' => t('Authored on'),
    '#maxlength' => 25,
    '#description' => t('Format: %time. The date format is YYYY-MM-DD and %timezone is the time zone offset from UTC. Leave blank to use the time of form submission.', array('%time' => !empty($file->date) ? date_format(date_create($file->date), 'Y-m-d H:i:s O') : format_date($file->created, 'custom', 'Y-m-d H:i:s O'), '%timezone' => !empty($file->date) ? date_format(date_create($file->date), 'O') : format_date($file->created, 'custom', 'O'))),
    '#default_value' => !empty($file->date) ? $file->date : '',
  );
  // File options for administrators
  $form['options'] = array(
    '#type' => 'fieldset',
    '#access' => user_access('administer files'),
    '#title' => t('Workflow'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'additional_settings',
    '#attributes' => array(
      'class' => array('file-entity-form-options'),
    ),
    '#weight' => 95,
  );
  $form['options']['published'] = array(
    '#type' => 'checkbox',
    '#title' => t('Published'),
    '#default_value' => $file->published,
  );
  $form['options']['promote'] = array(
    '#type' => 'checkbox',
    '#title' => t('Promoted'),
    '#default_value' => $file->promote,
  );
  $form['options']['sticky'] = array(
    '#type' => 'checkbox',
    '#title' => t('Sticky at the top of lists'),
    '#default_value' => $file->sticky,
  );
  $form['#validate'][] = 'file_admin_file_entity_edit_validate';
}

/**
 * Validate handler for file_entity_edit form.
 *
 * Prepare additional fields' data for saving to the file entity. Actual saving
 * is handled by file_entity_edit_submit().
 */
function file_admin_file_entity_edit_validate($form, &$form_state) {
  // Validate the "posted on" field.
  if (!empty($form_state['values']['date']) && strtotime($form_state['values']['date']) === FALSE) {
    form_set_error('date', t('You have to specify a valid date.'));
  }
  $name = trim($form_state['values']['name']);
  if (!empty($name) && $user = user_load_by_name($name)) {
    form_set_value($form['uid'], $user->uid, $form_state);
  }
  elseif (empty($name)) {
    form_set_value($form['uid'], 0, $form_state);
  }
  $created = !empty($form_state['values']['date']) ? strtotime($form_state['values']['date']) : time();
  form_set_value($form['created'], $created, $form_state);
}

/**
 * Implement hook_file_operations_info().
 */
function file_admin_file_operations_info() {
  $operations = array(
    'publish' => array(
      'label' => t('Publish'),
      'callback' => 'file_admin_mass_update',
      'callback arguments' => array('updates' => array('published' => FILE_NOT_PUBLISHED)),
    ),
    'unpublish' => array(
      'label' => t('Unpublish'),
      'callback' => 'file_admin_mass_update',
      'callback arguments' => array('updates' => array('published' => FILE_NOT_PUBLISHED)),
    ),
    'promote' => array(
      'label' => t('Promote selected files'),
      'callback' => 'file_admin_mass_update',
      'callback arguments' => array('updates' => array('published' => FILE_PUBLISHED, 'promote' => FILE_PROMOTED)),
    ),
    'demote' => array(
      'label' => t('Demote selected files'),
      'callback' => 'file_admin_mass_update',
      'callback arguments' => array('updates' => array('promote' => FILE_NOT_PROMOTED)),
    ),
  );

  return $operations;
}

/**
 * Make mass update of files, changing all files in the $files array
 * to update them with the field values in $updates.
 *
 * IMPORTANT NOTE: This function is intended to work when called
 * from a form submit handler. Calling it outside of the form submission
 * process may not work correctly.
 *
 * @param array $files
 *   Array of file fids to update.
 * @param array $updates
 *   Array of key/value pairs with file field names and the
 *   value to update that field to.
 */
function file_admin_mass_update($files, $updates) {
  // We use batch processing to prevent timeout when updating a large number
  // of files.
  if (count($files) > 10) {
    $batch = array(
      'operations' => array(
        array('_file_mass_update_batch_process', array($files, $updates))
      ),
      'finished' => '_file_mass_update_batch_finished',
      'title' => t('Processing'),
      // We use a single multi-pass operation, so the default
      // 'Remaining x of y operations' message will be confusing here.
      'progress_message' => '',
      'error_message' => t('The update has encountered an error.'),
      // The operations do not live in the .module file, so we need to
      // tell the batch engine which file to load before calling them.
      'file' => drupal_get_path('module', 'file_admin') . '/file.admin.inc',
    );
    batch_set($batch);
  }
  else {
    foreach ($files as $fid) {
      _file_mass_update_helper($fid, $updates);
    }
    drupal_set_message(t('The update has been performed.'));
  }
}

/**
 * File Mass Update - helper function.
 */
function _file_mass_update_helper($fid, $updates) {
  $file = file_load($fid, NULL, TRUE);
  // For efficiency manually save the original file before applying any changes.
  $file->original = clone $file;
  foreach ($updates as $name => $value) {
    $file->$name = $value;
  }
  file_save($file);
  return $file;
}

/**
 * File Mass Update Batch operation
 */
function _file_mass_update_batch_process($files, $updates, &$context) {
  if (!isset($context['sandbox']['progress'])) {
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['max'] = count($files);
    $context['sandbox']['files'] = $files;
  }

  // Process files by groups of 5.
  $count = min(5, count($context['sandbox']['files']));
  for ($i = 1; $i <= $count; $i++) {
    // For each fid, load the file, reset the values, and save it.
    $fid = array_shift($context['sandbox']['files']);
    $file = _file_mass_update_helper($fid, $updates);

    // Store result for post-processing in the finished callback.
    $context['results'][] = l($file->title, 'file/' . $file->fid);

    // Update our progress information.
    $context['sandbox']['progress']++;
  }

  // Inform the batch engine that we are not finished,
  // and provide an estimation of the completion level we reached.
  if ($context['sandbox']['progress'] != $context['sandbox']['max']) {
    $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
  }
}

/**
 * File Mass Update Batch 'finished' callback.
 */
function _file_mass_update_batch_finished($success, $results, $operations) {
  if ($success) {
    drupal_set_message(t('The update has been performed.'));
  }
  else {
    drupal_set_message(t('An error occurred and processing did not complete.'), 'error');
    $message = format_plural(count($results), '1 item successfully processed:', '@count items successfully processed:');
    $message .= theme('item_list', array('items' => $results));
    drupal_set_message($message);
  }
}

