; Drupal version
core = 7.x
api = 2

; Contrib modules
projects[addressfield][subdir] = contrib
projects[addressfield][version] = 1.0-beta3
projects[apps_compatible][subdir] = contrib
projects[apps_compatible][version] = 1.0-alpha2
projects[better_exposed_filters][subdir] = contrib
projects[better_exposed_filters][version] = 3.0-beta1
projects[context][subdir] = contrib
projects[context][version] = 3.0-beta4
projects[ctools][subdir] = contrib
projects[ctools][version] = 1.2
;projects[debut_location][subdir] = contrib
;projects[debut_location][version] = 1.x-dev
projects[features][subdir] = contrib
projects[features][version] = 1.0
projects[geocoder][subdir] = contrib
projects[geocoder][version] = 1.2
projects[geofield][subdir] = contrib
; No stable 2.x release yet. Use one when it's available.
projects[geofield][version] = 2.x-dev
projects[geophp][subdir] = contrib
; Use dev release until the first stble release after 1.6
; for the fix to http://drupal.org/node/1774098.
projects[geophp][version] = 1.x-dev
projects[openlayers][subdir] = contrib
; Using dev for fixes to marker tokens.
; Switch back to stable with first release after 2.0-beta1.
projects[openlayers][version] = 2.x-dev
projects[strongarm][subdir] = contrib
projects[strongarm][version] = 2.0
projects[views][subdir] = contrib
projects[views][version] = 3.5
