; Drupal version
core = 7.x
api = 2

; Contrib modules
projects[apps_compatible][subdir] = contrib
projects[apps_compatible][version] = 1.0-alpha1
projects[ctools][subdir] = contrib
projects[ctools][version] = 1.0
projects[debut_seo][subdir] = contrib
projects[debut_seo][version] = 1.0-rc2
projects[features][subdir] = contrib
projects[features][version] = 1.0
projects[globalredirect][subdir] = contrib
projects[globalredirect][version] = 1.5
projects[metatag][subdir] = contrib
projects[metatag][version] = 1.0-alpha7
projects[pathauto][subdir] = contrib
projects[pathauto][version] = 1.1
projects[token][subdir] = contrib
projects[token][version] = 1.1
projects[xmlsitemap][subdir] = contrib
projects[xmlsitemap][version] = 2.0-rc1

